### ISSUE TITLE
Update messed up formatting of outgoing emails

### ISSUE THREAD

**Issue by quikeagle** [k9mail/k-9#1982]
### Expected behavior
Tell us what should happen
Utilizing group share for gmail app - sends bcc group to new outgoing email in k-9 and then paste content and send
### Actual behavior
Tell us what happens instead
looks OK but all bcc show up in received email and content is not in sent format but looks like HTML code

I have attached screen shots from web gmail showing what was apparently sent (by k-9) as opposed to what was actually received.

![received](https://cloud.githubusercontent.com/assets/12779456/21687395/5e5918da-d326-11e6-83eb-70f1d66a3b5a.GIF)
![sent](https://cloud.githubusercontent.com/assets/12779456/21687396/5e594c6a-d326-11e6-8425-72f87153eaf4.GIF)

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:5.201

Android version:7

Account type (IMAP, POP3, WebDAV/Exchange):IMAP

**Comment by cketti** [comment]
The BCC information is accidentally included in the sent message. See #1938.
The display issue is caused by the BCC header line being really long. See #822.

**Comment by quikeagle** [comment]
I don't understand why I have been using it this way for years and it SUDDENLY quit working properly.  Apparently, this is an issue you have been aware of for some time, and yet it did not affect me until the recent update...

**Comment by Valodim** [comment]
Not sure what makes you think we have been aware of this issue for a long time? This was a regression that has been in development code for a while, yes, but the first release it was in was around christmas, we received the report three days ago, and it is now fixed. Please keep in mind we're not running a business operation here.

**Comment by quikeagle** [comment]
Sorry, I am not trying to be critical - I am trying to understand.  I was referred to #822 which is dated 9/30/15.  Maybe I misunderstood.  So, you say it is now fixed?  I first saw the problem this morning.  Shall I test again to see if the problem recreates itself for me?  If it is fixed, I am very grateful!

**Comment by Valodim** [comment]
Oh, I see what you mean. The problem you described here was the consequence of two bugs, one of them about header line length which is old, hardly critical (after all, it hasn't really come up in years) and not super easy to fix. The other is very recent, quite critical (leaking bcc info to recipients!), and simple to fix. That second bug was fixed in a release made today, so things should now be working at least as they were before for you :)

**Comment by quikeagle** [comment]
Ha!  I ran a test and it was still broken!  It might've been a good idea to update the app FIRST before trying another test!  Now all is well!  Thank you so much!

**Comment by Valodim** [comment]
happy to help! :)
