### ISSUE TITLE
Edge-to-edge regression - Move to/Copy to screen - Folder list hidden when 3-buttons navigation

### ISSUE THREAD

**Issue by zWhdmB5T** [k9mail/k-9#9850]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

12.1

### Where did you get the app from?

F-Droid

### Android version

Graphene OS: Android 16 (Build 2025091900)

### Device model

Google Pixel 6a

### Steps to reproduce

1. open Thunderbird for Android
2. open specific e-mail
3. use `move message` or `copy message`
4. try to move or copy the message to the folder in the _last_ row
5. it's not reachable: there is displayed the Android navigation bar (3 buttons)

### Expected behavior

1. the last row is also reachable (and clickable)
2. the last row is clearly _above_ the Android navigation bar (3 buttons)
3. some other apps do it better! (most apps on my system, indeed!)

### Actual behavior

1. the last row is covered and so hidden by the Android navigation bar (3 buttons)
2. one screen is actually OK, indeed: namely the configuring folders screen — but not the e-mail manager itself

### Logs

<img width="50%" alt="Image" src="https://github.com/user-attachments/assets/95d3695b-2512-4ed8-8fbb-33f5514853af" />
<img width="50%" alt="Image" src="https://github.com/user-attachments/assets/f5107cf7-fe88-42a9-b2df-1a6a73e2421a" />
<img width="50%" alt="Image" src="https://github.com/user-attachments/assets/47ae9525-ecbc-4c56-a12a-dac25a690a0e" />

<details>
<summary>3rd party apps</summary>

<img width="50%" alt="Image" src="https://github.com/user-attachments/assets/7c679ff8-f74a-4a5d-9414-f9da4aae08e2" />
<img width="50%" alt="Image" src="https://github.com/user-attachments/assets/15b8e8d7-02b3-4feb-9d5c-55efd1a7c166" />
<img width="50%" alt="Image" src="https://github.com/user-attachments/assets/c651e8fc-c4d8-4c17-8410-1da00cae49ad" />
<img width="50%" alt="Image" src="https://github.com/user-attachments/assets/44252d9f-cc01-4310-a5f4-bb17700de031" />
<img width="50%" alt="Image" src="https://github.com/user-attachments/assets/2083092e-6721-4b9c-a4e3-868e7678edd0" />
<img width="50%" alt="Image" src="https://github.com/user-attachments/assets/f0bb9c44-3880-4fa6-8aad-51588cc4f6cb" />
<img width="50%" alt="Image" src="https://github.com/user-attachments/assets/eaea47c2-823c-46ac-ad4c-bb94e547a56a" />
<img width="50%" alt="Image" src="https://github.com/user-attachments/assets/f925388e-230c-42f0-8130-52f1d59dc2e3" />
<img width="50%" alt="Image" src="https://github.com/user-attachments/assets/5be50a9f-d9ed-41d6-b30e-52814fcda0e9" />
</details>

**Comment by platform34** [comment]
The images of all the 3rd party software obscures what @zWhdmB5T is attempting to report here.

This appears to be another two "edge-to-edge regression" cases not identified before or fixed by #9614 .
The last folder is hidden beneath the 3 button navigation menu when moving or copying a message.  The issue is similar to #9612 

I can reproduce on 12.1 and 13.0b3

1. Change to an account inbox
2. Open a message
3. Select **move** or **copy** from the 3dot menu.
4. The Folder list is displayed. 
Observe the last folder is obscured beneath the 3 button navigation menu

**Comment by zWhdmB5T** [comment]
@platform34 Thank you very much for confirming and offering details! Appreciated!

**Comment by zWhdmB5T** [comment]
I just wanted to say "Thank you folks for working on this!"

**Comment by zWhdmB5T** [comment]
Thank you!

**Comment by zWhdmB5T** [comment]
@rafaeltonholo @asoucar Please, reopen this issue!

See below: issue stills persists.

@platform34 Can you please check again, like last time.

<details>
<summary>main menu, it's correct here</summary>
<img width="864" height="1920" alt="Image" src="https://github.com/user-attachments/assets/13b0b1f6-8807-49d3-a983-5fde7647219e" />
<img width="864" height="1920" alt="Image" src="https://github.com/user-attachments/assets/a99a2817-8fae-4e4e-9d18-fe3df8285a3f" />
</details>

<details>
<summary>context menu for message, it's incorrect there</summary>
<img width="864" height="1920" alt="Image" src="https://github.com/user-attachments/assets/aa1d4813-6589-473e-84b0-0a348ab5fd58" />
<img width="864" height="1920" alt="Image" src="https://github.com/user-attachments/assets/ac2e944a-9a92-44de-bc5b-51f45d39b474" />
<img width="864" height="1920" alt="Image" src="https://github.com/user-attachments/assets/0eb40b04-dff4-4ff4-bc53-1e520830a671" />
<img width="864" height="1920" alt="Image" src="https://github.com/user-attachments/assets/a189596c-3318-4603-83e0-09713a48c9df" />
<img width="864" height="1920" alt="Image" src="https://github.com/user-attachments/assets/fa92525a-85f7-43a5-b675-f13f365c80c2" />
</details>

**Comment by zWhdmB5T** [comment]
Finally resolved in v14. Thank you!
